import { Roboto, Noto_Sans_SC } from 'next/font/google';
import "./globals.css";
import 'antd/dist/reset.css';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: "--font-roboto",
});

const notoSans = Noto_Sans_SC({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-noto-sans",
});

export const metadata = {
  icons: "/favicon.ico",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${notoSans.variable} antialiased`}>
        body begin
        {children}
        body end
      </body>
    </html>
  );
}
