// import { Roboto, Noto_Sans_SC } from 'next/font/google';
import "./globals.css";
import ThemeProvider from '@/app/components/theme/themeProvider';

// const roboto = Roboto({
//   subsets: ['latin'],
//   weight: ['100', '400', '700'], 
//   variable: "--font-roboto",
// });

// const notoSans = Noto_Sans_SC({
//   subsets: ['latin'],
//   weight: ['100', '400', '700'],
//   variable: "--font-noto-sans",
// });

export const metadata = {
  icons: "/favicon.ico",
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={`${roboto.variable} antialiased`}> */}
      <body className={` antialiased`}>
        body begin
        <ThemeProvider/>
        {children}
        body end
      </body>
    </html>
  );
}
